local dap = require "dap"

-- dap.adapters.codelldb = {
--   type = "server",
--   port = "13000",
--   executable = {
--     -- Change this to your path!
--     command = "/opt/codelldb/adapter/codelldb",
--     args = { "--port", "13000" },
--   },
-- }
--
-- dap.configurations.rust = {
--   {
--     name = "Launch file",
--     type = "codelldb",
--     request = "launch",
--     program = function()
--       return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/target/debug/", "file")
--     end,
--     cwd = "${workspaceFolder}",
--     stopOnEntry = false,
--   },
-- }
